// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: movie_event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_VIEW_STARTED           EventType = 1
	EventType_VIEW_FINISHED          EventType = 2
	EventType_VIEW_PAUSED            EventType = 3
	EventType_VIEW_RESUMED           EventType = 4
	EventType_LIKED                  EventType = 5
	EventType_SEARCHED               EventType = 6
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "VIEW_STARTED",
		2: "VIEW_FINISHED",
		3: "VIEW_PAUSED",
		4: "VIEW_RESUMED",
		5: "LIKED",
		6: "SEARCHED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"VIEW_STARTED":           1,
		"VIEW_FINISHED":          2,
		"VIEW_PAUSED":            3,
		"VIEW_RESUMED":           4,
		"LIKED":                  5,
		"SEARCHED":               6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_movie_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_movie_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_movie_event_proto_rawDescGZIP(), []int{0}
}

type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_MOBILE                  DeviceType = 1
	DeviceType_DESKTOP                 DeviceType = 2
	DeviceType_TV                      DeviceType = 3
	DeviceType_TABLET                  DeviceType = 4
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "MOBILE",
		2: "DESKTOP",
		3: "TV",
		4: "TABLET",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"MOBILE":                  1,
		"DESKTOP":                 2,
		"TV":                      3,
		"TABLET":                  4,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_movie_event_proto_enumTypes[1].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_movie_event_proto_enumTypes[1]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_movie_event_proto_rawDescGZIP(), []int{1}
}

type MovieEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId         string                 `protobuf:"bytes,3,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	EventType       EventType              `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=cinema.EventType" json:"event_type,omitempty"`
	TimestampMs     int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	DeviceType      DeviceType             `protobuf:"varint,6,opt,name=device_type,json=deviceType,proto3,enum=cinema.DeviceType" json:"device_type,omitempty"`
	SessionId       string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProgressSeconds int32                  `protobuf:"varint,8,opt,name=progress_seconds,json=progressSeconds,proto3" json:"progress_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MovieEvent) Reset() {
	*x = MovieEvent{}
	mi := &file_movie_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieEvent) ProtoMessage() {}

func (x *MovieEvent) ProtoReflect() protoreflect.Message {
	mi := &file_movie_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieEvent.ProtoReflect.Descriptor instead.
func (*MovieEvent) Descriptor() ([]byte, []int) {
	return file_movie_event_proto_rawDescGZIP(), []int{0}
}

func (x *MovieEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MovieEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MovieEvent) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *MovieEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *MovieEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MovieEvent) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *MovieEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MovieEvent) GetProgressSeconds() int32 {
	if x != nil {
		return x.ProgressSeconds
	}
	return 0
}

var File_movie_event_proto protoreflect.FileDescriptor

const file_movie_event_proto_rawDesc = "" +
	"\n" +
	"\x11movie_event.proto\x12\x06cinema\"\xaf\x02\n" +
	"\n" +
	"MovieEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x03 \x01(\tR\amovieId\x120\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2\x11.cinema.EventTypeR\teventType\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x123\n" +
	"\vdevice_type\x18\x06 \x01(\x0e2\x12.cinema.DeviceTypeR\n" +
	"deviceType\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\x12)\n" +
	"\x10progress_seconds\x18\b \x01(\x05R\x0fprogressSeconds*\x88\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fVIEW_STARTED\x10\x01\x12\x11\n" +
	"\rVIEW_FINISHED\x10\x02\x12\x0f\n" +
	"\vVIEW_PAUSED\x10\x03\x12\x10\n" +
	"\fVIEW_RESUMED\x10\x04\x12\t\n" +
	"\x05LIKED\x10\x05\x12\f\n" +
	"\bSEARCHED\x10\x06*V\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06MOBILE\x10\x01\x12\v\n" +
	"\aDESKTOP\x10\x02\x12\x06\n" +
	"\x02TV\x10\x03\x12\n" +
	"\n" +
	"\x06TABLET\x10\x04B&Z$github.com/online-cinema/producer/pbb\x06proto3"

var (
	file_movie_event_proto_rawDescOnce sync.Once
	file_movie_event_proto_rawDescData []byte
)

func file_movie_event_proto_rawDescGZIP() []byte {
	file_movie_event_proto_rawDescOnce.Do(func() {
		file_movie_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_event_proto_rawDesc), len(file_movie_event_proto_rawDesc)))
	})
	return file_movie_event_proto_rawDescData
}

var file_movie_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_movie_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_movie_event_proto_goTypes = []any{
	(EventType)(0),     // 0: cinema.EventType
	(DeviceType)(0),    // 1: cinema.DeviceType
	(*MovieEvent)(nil), // 2: cinema.MovieEvent
}
var file_movie_event_proto_depIdxs = []int32{
	0, // 0: cinema.MovieEvent.event_type:type_name -> cinema.EventType
	1, // 1: cinema.MovieEvent.device_type:type_name -> cinema.DeviceType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_movie_event_proto_init() }
func file_movie_event_proto_init() {
	if File_movie_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_event_proto_rawDesc), len(file_movie_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_movie_event_proto_goTypes,
		DependencyIndexes: file_movie_event_proto_depIdxs,
		EnumInfos:         file_movie_event_proto_enumTypes,
		MessageInfos:      file_movie_event_proto_msgTypes,
	}.Build()
	File_movie_event_proto = out.File
	file_movie_event_proto_goTypes = nil
	file_movie_event_proto_depIdxs = nil
}
