apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: app
      defaultDatabase: default
      secure: false
    secureJsonData:
      password: app

